services:
   db-device:
    image: postgres
    container_name: db-device
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: device-microservice
    ports:
      - "5433:5432"
    volumes:
      - my-db-device:/var/lib/postgresql/data
    networks:
      - demo_net

   db-user:
    image: postgres
    container_name: db-user
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user-microservice
    ports:
      - "5434:5432"
    volumes:
      - my-db-user:/var/lib/postgresql/data
    networks:
      - demo_net

   db-auth:
    image: postgres
    container_name: db-auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth-microservice
    ports:
      - "5435:5432"
    volumes:
      - my-db-auth:/var/lib/postgresql/data
    networks:
      - demo_net

   db-monitoring:
    image: postgres
    container_name: db-monitoring
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: monitoring-microservice
    ports:
      - "5436:5432"
    volumes:
      - my-db-monitoring:/var/lib/postgresql/data
    networks:
      - demo_net

   device-microservice:
    image: devicemicro2
    container_name: device-microservice
    environment:
      - DB_IP=db-device
      - DB_PORT=5432
      - DB_DBNAME=device-microservice
      - DB_USER=postgres
      - DB_PASSWORD=admin
    networks:
      - demo_net

   user-microservice:
    image: usermicro2
    container_name: user-microservice
    environment:
      - DB_IP=db-user
      - DB_PORT=5432
      - DB_DBNAME=user-microservice
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DEVICE_MS_BASE_URL=http://device-microservice:8080
    networks:
      - demo_net

   auth-microservice:
    build:
      context: ./auth-microservice/demo
      dockerfile: Dockerfile
    image: authmicro2
    container_name: auth-microservice
    environment:
      - DB_IP=db-auth
      - DB_PORT=5432
      - DB_DBNAME=auth-microservice
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - PORT=8080
      - DEVICE_MS_BASE_URL=http://device-microservice:8080
      - USER_MICROSERVICE_BASE_URL=http://user-microservice:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
    networks:
      - demo_net
    depends_on:
      - db-auth

   monitoring-microservice:
    build:
      context: ./monitoring-microservice/demo
      dockerfile: Dockerfile
    image: monitoringmicro2
    container_name: monitoring-microservice
    environment:
      - DB_IP=db-monitoring
      - DB_PORT=5432
      - DB_DBNAME=monitoring-microservice
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - PORT=8080
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=kalo
      - RABBITMQ_PASSWORD=kalo
      - USER_MICROSERVICE_BASE_URL=http://user-microservice:8080
    networks:
      - demo_net
    depends_on:
      - db-monitoring
      - rabbitmq

   frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    environment:
      - VITE_API_BASE_URL=http://localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`) && !PathPrefix(`/api/auth`) && !PathPrefix(`/users`) && !PathPrefix(`/device`) && !PathPrefix(`/api-docs`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - demo_net

   api-docs:
    build:
      context: ./api-docs
      dockerfile: Dockerfile
    image: api-docs
    container_name: api-docs
    networks:
      - demo_net

   rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - demo_net

   traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Traefik can listen to the Docker events
      - "./traefik.yml:/etc/traefik/traefik.yml:ro" # Static configuration file
      - "./dynamic:/etc/traefik/dynamic:ro" # Dynamic configuration files
      - "./logs:/var/log/traefik" # Log files
    develop: # Enable live reload of dynamic configuration files on Windows, if using Unix based system needs to be commented out
      watch:
       - path: ./dynamic                   # watch the whole folder
         action: restart
    networks:
      - demo_net
  
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  my-db-device:
  my-db-user:
  my-db-auth:
  my-db-monitoring:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

networks:
  demo_net:
    driver: bridge
